import { assertEquals } from "https://deno.land/std@0.187.0/testing/asserts.ts";
import { cleanObj, simplifiedStation } from "./utils.ts";

Deno.test('clean obj', () => {
    const obj = {
    access_code: "public",
    access_days_time: "24 hours daily",
    access_detail_code: null,
    cards_accepted: null,
    date_last_confirmed: "2023-04-30",
    expected_date: "2022-09-21",
    fuel_type_code: "ELEC",
    groups_with_access_code: "TEMPORARILY UNAVAILABLE (Public)",
    id: 228137,
    open_date: "2018-03-07",
    owner_type_code: null,
    status_code: "T",
    restricted_access: null,
    station_name: "Whole Foods Market",
    station_phone: "877-455-3833",
    updated_at: "2023-04-30T23:55:57Z",
    facility_type: null,
    geocode_status: "GPS",
    latitude: 41.89505,
    longitude: -87.62899,
    city: "Chicago",
    intersection_directions: null,
    plus4: null,
    state: "IL",
    street_address: "30 W Huron St",
    zip: "60654",
    country: "US",
    bd_blends: null,
    cng_dispenser_num: null,
    cng_fill_type_code: null,
    cng_psi: null,
    cng_renewable_source: null,
    cng_total_compression: null,
    cng_total_storage: null,
    cng_vehicle_class: null,
    cng_has_rng: null,
    e85_blender_pump: null,
    e85_other_ethanol_blends: null,
    ev_connector_types: [ "J1772" ],
    ev_dc_fast_num: null,
    ev_level1_evse_num: null,
    ev_level2_evse_num: 2,
    ev_network: "eVgo Network",
    ev_network_web: "https://www.evgo.com/",
    ev_other_evse: null,
    ev_pricing: null,
    ev_renewable_source: null,
    hy_is_retail: null,
    hy_pressures: null,
    hy_standards: null,
    hy_status_link: null,
    lng_renewable_source: null,
    lng_vehicle_class: null,
    lng_has_rng: null,
    lpg_primary: null,
    lpg_nozzle_types: null,
    ng_fill_type_code: null,
    ng_psi: null,
    ng_vehicle_class: null,
    rd_blends: null,
    rd_blends_fr: null,
    rd_blended_with_biodiesel: null,
    rd_max_biodiesel_level: null,
    nps_unit_name: null,
    access_days_time_fr: null,
    intersection_directions_fr: null,
    bd_blends_fr: null,
    groups_with_access_code_fr: "TEMPORAIREMENT SUSPENDU (Public)",
    ev_pricing_fr: null,
    ev_network_ids: { station: [ "228" ], posts: [ "56161", "56162" ] }
  }
  const test: simplifiedStation = {
    access_code: "public",
    access_days_time: "24 hours daily",
    date_last_confirmed: "2023-04-30",
    expected_date: "2022-09-21",
    fuel_type_code: "ELEC",
    id: 228137,
    open_date: "2018-03-07",
    station_name: "Whole Foods Market",
    updated_at: "2023-04-30T23:55:57Z",
    latitude: 41.89505,
    longitude: -87.62899,
    city: "Chicago",
    state: "IL",
    street_address: "30 W Huron St",
    zip: "60654",
    country: "US",
    ev_connector_types: [ "J1772" ],
    ev_level1_evse_num: null,
    ev_level2_evse_num: 2,
    ev_network: "eVgo Network",
  }
    assertEquals(cleanObj(obj), test)
})